# Generated by Django 4.0.6 on 2022-10-14 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('EDV', models.CharField(max_length=10)),
                ('id_card', models.CharField(blank=True, default=0, max_length=30, null=True)),
                ('skill', models.BooleanField(default=False)),
                ('skill2', models.BooleanField(default=False)),
                ('adminU', models.BooleanField(default=False)),
                ('birth', models.DateField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeJob', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
                ('ipaddress', models.CharField(max_length=20)),
                ('statusMaint', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('InitialHour', models.TimeField()),
                ('FinishHour', models.TimeField(blank=True, null=True)),
                ('idAssociateFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associateReleaseMachine', to='api.associate')),
                ('idMachineFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machineReleaseMachine', to='api.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('description', models.CharField(max_length=500)),
                ('idAssociateFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associateObservation', to='api.associate')),
                ('idMachineFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machineObservation', to='api.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Initialhour', models.TimeField()),
                ('Finishhour', models.TimeField(blank=True, null=True)),
                ('idAssociateFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associate', to='api.associate')),
                ('idMachineFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machineMaintenance', to='api.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('edv', models.CharField(max_length=200)),
                ('idAreaFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areaLogin', to='api.areas')),
            ],
        ),
        migrations.CreateModel(
            name='GreenBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('idMachineFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machineGreenBook', to='api.machine')),
                ('typeQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='api.question')),
            ],
        ),
        migrations.AddField(
            model_name='associate',
            name='jobposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobPositon', to='api.jobposition'),
        ),
    ]
