# Generated by Django 4.0.6 on 2022-10-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasemachine',
            name='examA',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='releasemachine',
            name='examB',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='releasemachine',
            name='result',
            field=models.CharField(default='', max_length=10),
        ),
    ]
