# Generated by Django 4.0.6 on 2022-11-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_maintenance_statusmaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='statusMaint',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
